#############################################################################
# Makefile for building: tlen
# Generated by qmake (2.01a) (Qt 4.5.2) on: niedz. wrz 20 07:12:26 2009
# Project:  tlen.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile tlen.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_DBUS_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtDBus -I/usr/include/qt4 -I. -Iwidgets -I/usr/include/QtCrypto -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib ssl qca -lQtDBus -lQtSql -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = chat_manager.cpp \
		debug.cpp \
		edit_dialog.cpp \
		form1.cpp \
		info_edit.cpp \
		main.cpp \
		qtlen.cpp \
		qtlen_parser.cpp \
		roster_manager.cpp \
		settings_dialog.cpp \
		sha1.cpp \
		widgets/qtlenchatwindow.cpp \
		widgets/qtlenmainwindow.cpp \
		widgets/qtlenrosterbox.cpp \
		widgets/qtlentextedit.cpp \
		widgets/systrayicon.cpp \
		widgets/qtlensearchresultbox.cpp \
		widgets/qtlensearchdialog.cpp \
		avatarsmanager.cpp \
		historymanager.cpp \
		widgets/qtlenstatuslabel.cpp \
		widgets/qtlenavatarlabel.cpp \
		widgets/qtlenpublicchatswindow.cpp \
		qtlenpublicchatsmanager.cpp \
		qtlencryptedsocket.cpp \
		widgets/qtlenchatcontainer.cpp \
		widgets/qtlenrosteritem.cpp \
		widgets/qtlenrosteritemdelegate.cpp moc_chat_manager.cpp \
		moc_debug.cpp \
		moc_edit_dialog.cpp \
		moc_form1.cpp \
		moc_info_edit.cpp \
		moc_qtlen.cpp \
		moc_roster_manager.cpp \
		moc_settings_dialog.cpp \
		moc_qtlenchatwindow.cpp \
		moc_qtlenmainwindow.cpp \
		moc_qtlenrosterbox.cpp \
		moc_qtlentextedit.cpp \
		moc_systrayicon.cpp \
		moc_qtlensearchresultbox.cpp \
		moc_qtlensearchdialog.cpp \
		moc_avatarsmanager.cpp \
		moc_historymanager.cpp \
		moc_qtlenstatuslabel.cpp \
		moc_qtlenavatarlabel.cpp \
		moc_qtlencryptedsocket.cpp \
		moc_qtlenchatcontainer.cpp \
		moc_qtlenrosteritemdelegate.cpp \
		qrc_icons.cpp
OBJECTS       = chat_manager.o \
		debug.o \
		edit_dialog.o \
		form1.o \
		info_edit.o \
		main.o \
		qtlen.o \
		qtlen_parser.o \
		roster_manager.o \
		settings_dialog.o \
		sha1.o \
		qtlenchatwindow.o \
		qtlenmainwindow.o \
		qtlenrosterbox.o \
		qtlentextedit.o \
		systrayicon.o \
		qtlensearchresultbox.o \
		qtlensearchdialog.o \
		avatarsmanager.o \
		historymanager.o \
		qtlenstatuslabel.o \
		qtlenavatarlabel.o \
		qtlenpublicchatswindow.o \
		qtlenpublicchatsmanager.o \
		qtlencryptedsocket.o \
		qtlenchatcontainer.o \
		qtlenrosteritem.o \
		qtlenrosteritemdelegate.o \
		moc_chat_manager.o \
		moc_debug.o \
		moc_edit_dialog.o \
		moc_form1.o \
		moc_info_edit.o \
		moc_qtlen.o \
		moc_roster_manager.o \
		moc_settings_dialog.o \
		moc_qtlenchatwindow.o \
		moc_qtlenmainwindow.o \
		moc_qtlenrosterbox.o \
		moc_qtlentextedit.o \
		moc_systrayicon.o \
		moc_qtlensearchresultbox.o \
		moc_qtlensearchdialog.o \
		moc_avatarsmanager.o \
		moc_historymanager.o \
		moc_qtlenstatuslabel.o \
		moc_qtlenavatarlabel.o \
		moc_qtlencryptedsocket.o \
		moc_qtlenchatcontainer.o \
		moc_qtlenrosteritemdelegate.o \
		qrc_icons.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		tlen.pro
QMAKE_TARGET  = tlen
DESTDIR       = 
TARGET        = tlen

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_config.h ui_debug.h ui_info_edit.h ui_user_edit.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: tlen.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtDBus.prl \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile tlen.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/dbusinterfaces.prf:
/usr/share/qt4/mkspecs/features/dbusadaptors.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtDBus.prl:
/usr/lib/libQtSql.prl:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile tlen.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/tlen1.0.0 || $(MKDIR) .tmp/tlen1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/tlen1.0.0/ && $(COPY_FILE) --parents chat_manager.h debug.h defines.h edit_dialog.h form1.h info_edit.h qtlen.h qtlen_parser.h roster_manager.h settings_dialog.h sha1.h widgets/qtlenchatwindow.hpp widgets/qtlenmainwindow.hpp widgets/qtlenrosterbox.hpp widgets/qtlentextedit.hpp widgets/systrayicon.h widgets/qtlensearchresultbox.hpp widgets/qtlensearchdialog.hpp avatarsmanager.hpp historymanager.hpp widgets/qtlenstatuslabel.hpp widgets/qtlenavatarlabel.hpp widgets/qtlenpublicchatswindow.hpp qtlenpublicchatsmanager.hpp qtlencryptedsocket.h widgets/qtlenchatcontainer.hpp widgets/qtlenrosteritem.hpp widgets/qtlenrosteritemdelegate.hpp .tmp/tlen1.0.0/ && $(COPY_FILE) --parents icons.qrc .tmp/tlen1.0.0/ && $(COPY_FILE) --parents chat_manager.cpp debug.cpp edit_dialog.cpp form1.cpp info_edit.cpp main.cpp qtlen.cpp qtlen_parser.cpp roster_manager.cpp settings_dialog.cpp sha1.cpp widgets/qtlenchatwindow.cpp widgets/qtlenmainwindow.cpp widgets/qtlenrosterbox.cpp widgets/qtlentextedit.cpp widgets/systrayicon.cpp widgets/qtlensearchresultbox.cpp widgets/qtlensearchdialog.cpp avatarsmanager.cpp historymanager.cpp widgets/qtlenstatuslabel.cpp widgets/qtlenavatarlabel.cpp widgets/qtlenpublicchatswindow.cpp qtlenpublicchatsmanager.cpp qtlencryptedsocket.cpp widgets/qtlenchatcontainer.cpp widgets/qtlenrosteritem.cpp widgets/qtlenrosteritemdelegate.cpp .tmp/tlen1.0.0/ && $(COPY_FILE) --parents config.ui debug.ui info_edit.ui user_edit.ui .tmp/tlen1.0.0/ && $(COPY_FILE) --parents qtlen4_pl.ts .tmp/tlen1.0.0/ && (cd `dirname .tmp/tlen1.0.0` && $(TAR) tlen1.0.0.tar tlen1.0.0 && $(COMPRESS) tlen1.0.0.tar) && $(MOVE) `dirname .tmp/tlen1.0.0`/tlen1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/tlen1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_chat_manager.cpp moc_debug.cpp moc_edit_dialog.cpp moc_form1.cpp moc_info_edit.cpp moc_qtlen.cpp moc_roster_manager.cpp moc_settings_dialog.cpp moc_qtlenchatwindow.cpp moc_qtlenmainwindow.cpp moc_qtlenrosterbox.cpp moc_qtlentextedit.cpp moc_systrayicon.cpp moc_qtlensearchresultbox.cpp moc_qtlensearchdialog.cpp moc_avatarsmanager.cpp moc_historymanager.cpp moc_qtlenstatuslabel.cpp moc_qtlenavatarlabel.cpp moc_qtlencryptedsocket.cpp moc_qtlenchatcontainer.cpp moc_qtlenrosteritemdelegate.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_chat_manager.cpp moc_debug.cpp moc_edit_dialog.cpp moc_form1.cpp moc_info_edit.cpp moc_qtlen.cpp moc_roster_manager.cpp moc_settings_dialog.cpp moc_qtlenchatwindow.cpp moc_qtlenmainwindow.cpp moc_qtlenrosterbox.cpp moc_qtlentextedit.cpp moc_systrayicon.cpp moc_qtlensearchresultbox.cpp moc_qtlensearchdialog.cpp moc_avatarsmanager.cpp moc_historymanager.cpp moc_qtlenstatuslabel.cpp moc_qtlenavatarlabel.cpp moc_qtlencryptedsocket.cpp moc_qtlenchatcontainer.cpp moc_qtlenrosteritemdelegate.cpp
moc_chat_manager.cpp: widgets/qtlenchatcontainer.hpp \
		widgets/qtlenchatwindow.hpp \
		widgets/qtlentextedit.hpp \
		defines.h \
		roster_manager.h \
		widgets/qtlenrosterbox.hpp \
		widgets/qtlenrosteritemdelegate.hpp \
		widgets/qtlenrosteritem.hpp \
		widgets/systrayicon.h \
		avatarsmanager.hpp \
		historymanager.hpp \
		chat_manager.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) chat_manager.h -o moc_chat_manager.cpp

moc_debug.cpp: ui_debug.h \
		debug.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) debug.h -o moc_debug.cpp

moc_edit_dialog.cpp: ui_user_edit.h \
		edit_dialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) edit_dialog.h -o moc_edit_dialog.cpp

moc_form1.cpp: qtlen.h \
		qtlencryptedsocket.h \
		defines.h \
		qtlen_parser.h \
		widgets/systrayicon.h \
		widgets/qtlenmainwindow.hpp \
		widgets/qtlenrosterbox.hpp \
		widgets/qtlenrosteritemdelegate.hpp \
		widgets/qtlenrosteritem.hpp \
		widgets/qtlenstatuslabel.hpp \
		widgets/qtlentextedit.hpp \
		widgets/qtlenavatarlabel.hpp \
		chat_manager.h \
		widgets/qtlenchatcontainer.hpp \
		widgets/qtlenchatwindow.hpp \
		roster_manager.h \
		avatarsmanager.hpp \
		historymanager.hpp \
		debug.h \
		ui_debug.h \
		edit_dialog.h \
		ui_user_edit.h \
		settings_dialog.h \
		info_edit.h \
		ui_info_edit.h \
		widgets/qtlensearchdialog.hpp \
		widgets/qtlensearchresultbox.hpp \
		widgets/qtlenpublicchatswindow.hpp \
		form1.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) form1.h -o moc_form1.cpp

moc_info_edit.cpp: ui_info_edit.h \
		defines.h \
		info_edit.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) info_edit.h -o moc_info_edit.cpp

moc_qtlen.cpp: qtlencryptedsocket.h \
		defines.h \
		qtlen_parser.h \
		qtlen.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qtlen.h -o moc_qtlen.cpp

moc_roster_manager.cpp: defines.h \
		widgets/qtlenrosterbox.hpp \
		widgets/qtlenrosteritemdelegate.hpp \
		widgets/qtlenrosteritem.hpp \
		widgets/systrayicon.h \
		avatarsmanager.hpp \
		roster_manager.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) roster_manager.h -o moc_roster_manager.cpp

moc_settings_dialog.cpp: defines.h \
		settings_dialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) settings_dialog.h -o moc_settings_dialog.cpp

moc_qtlenchatwindow.cpp: widgets/qtlentextedit.hpp \
		defines.h \
		widgets/qtlenchatwindow.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) widgets/qtlenchatwindow.hpp -o moc_qtlenchatwindow.cpp

moc_qtlenmainwindow.cpp: widgets/qtlenrosterbox.hpp \
		widgets/qtlenrosteritemdelegate.hpp \
		widgets/qtlenrosteritem.hpp \
		defines.h \
		widgets/qtlenstatuslabel.hpp \
		widgets/qtlentextedit.hpp \
		widgets/qtlenavatarlabel.hpp \
		widgets/qtlenmainwindow.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) widgets/qtlenmainwindow.hpp -o moc_qtlenmainwindow.cpp

moc_qtlenrosterbox.cpp: widgets/qtlenrosteritemdelegate.hpp \
		widgets/qtlenrosteritem.hpp \
		defines.h \
		widgets/qtlenrosterbox.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) widgets/qtlenrosterbox.hpp -o moc_qtlenrosterbox.cpp

moc_qtlentextedit.cpp: widgets/qtlentextedit.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) widgets/qtlentextedit.hpp -o moc_qtlentextedit.cpp

moc_systrayicon.cpp: widgets/systrayicon.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) widgets/systrayicon.h -o moc_systrayicon.cpp

moc_qtlensearchresultbox.cpp: defines.h \
		widgets/qtlensearchresultbox.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) widgets/qtlensearchresultbox.hpp -o moc_qtlensearchresultbox.cpp

moc_qtlensearchdialog.cpp: defines.h \
		widgets/qtlensearchresultbox.hpp \
		widgets/qtlensearchdialog.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) widgets/qtlensearchdialog.hpp -o moc_qtlensearchdialog.cpp

moc_avatarsmanager.cpp: defines.h \
		avatarsmanager.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) avatarsmanager.hpp -o moc_avatarsmanager.cpp

moc_historymanager.cpp: defines.h \
		historymanager.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) historymanager.hpp -o moc_historymanager.cpp

moc_qtlenstatuslabel.cpp: widgets/qtlenstatuslabel.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) widgets/qtlenstatuslabel.hpp -o moc_qtlenstatuslabel.cpp

moc_qtlenavatarlabel.cpp: widgets/qtlenavatarlabel.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) widgets/qtlenavatarlabel.hpp -o moc_qtlenavatarlabel.cpp

moc_qtlencryptedsocket.cpp: qtlencryptedsocket.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qtlencryptedsocket.h -o moc_qtlencryptedsocket.cpp

moc_qtlenchatcontainer.cpp: widgets/qtlenchatwindow.hpp \
		widgets/qtlentextedit.hpp \
		defines.h \
		widgets/qtlenchatcontainer.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) widgets/qtlenchatcontainer.hpp -o moc_qtlenchatcontainer.cpp

moc_qtlenrosteritemdelegate.cpp: widgets/qtlenrosteritem.hpp \
		defines.h \
		widgets/qtlenrosteritemdelegate.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) widgets/qtlenrosteritemdelegate.hpp -o moc_qtlenrosteritemdelegate.cpp

compiler_dbus_interface_source_make_all:
compiler_dbus_interface_source_clean:
compiler_dbus_adaptor_source_make_all:
compiler_dbus_adaptor_source_clean:
compiler_rcc_make_all: qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp
qrc_icons.cpp: icons.qrc \
		icons/list-remove-user.png \
		icons/status_unknown.png \
		icons/view-history.png \
		icons/dialog-cancel.png \
		icons/list-add-user.png \
		icons/network-connect.png \
		icons/help-about.png \
		icons/network-disconnect.png \
		icons/configure.png \
		icons/application-exit.png \
		icons/meeting-attending.png \
		icons/user-properties.png \
		icons/view-user-offline-kopete.png \
		icons/preferences-plugin-script.png \
		icons/draw-freehand.png \
		icons/16x16/xa.png \
		icons/16x16/away.png \
		icons/16x16/offline.png \
		icons/16x16/online.png \
		icons/16x16/dnd.png \
		icons/16x16/chatty.png \
		icons/16x16/invisible.png \
		icons/64x64/roster.png \
		icons/64x64/default_av.png \
		icons/64x64/mask.png \
		icons/64x64/look.png \
		icons/64x64/network.png \
		icons/32x32/search.png \
		icons/32x32/xa.png \
		icons/32x32/add.png \
		icons/32x32/away.png \
		icons/32x32/clear.png \
		icons/32x32/offline.png \
		icons/32x32/online.png \
		icons/32x32/dnd.png \
		icons/32x32/chatty.png \
		icons/32x32/invisible.png
	/usr/bin/rcc -name icons icons.qrc -o qrc_icons.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_dbus_interface_header_make_all:
compiler_dbus_interface_header_clean:
compiler_dbus_interface_moc_make_all:
compiler_dbus_interface_moc_clean:
compiler_dbus_adaptor_header_make_all:
compiler_dbus_adaptor_header_clean:
compiler_dbus_adaptor_moc_make_all:
compiler_dbus_adaptor_moc_clean:
compiler_uic_make_all: ui_config.h ui_debug.h ui_info_edit.h ui_user_edit.h
compiler_uic_clean:
	-$(DEL_FILE) ui_config.h ui_debug.h ui_info_edit.h ui_user_edit.h
ui_config.h: config.ui
	/usr/bin/uic-qt4 config.ui -o ui_config.h

ui_debug.h: debug.ui
	/usr/bin/uic-qt4 debug.ui -o ui_debug.h

ui_info_edit.h: info_edit.ui
	/usr/bin/uic-qt4 info_edit.ui -o ui_info_edit.h

ui_user_edit.h: user_edit.ui
	/usr/bin/uic-qt4 user_edit.ui -o ui_user_edit.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

chat_manager.o: chat_manager.cpp chat_manager.h \
		widgets/qtlenchatcontainer.hpp \
		widgets/qtlenchatwindow.hpp \
		widgets/qtlentextedit.hpp \
		defines.h \
		roster_manager.h \
		widgets/qtlenrosterbox.hpp \
		widgets/qtlenrosteritemdelegate.hpp \
		widgets/qtlenrosteritem.hpp \
		widgets/systrayicon.h \
		avatarsmanager.hpp \
		historymanager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chat_manager.o chat_manager.cpp

debug.o: debug.cpp debug.h \
		ui_debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug.o debug.cpp

edit_dialog.o: edit_dialog.cpp edit_dialog.h \
		ui_user_edit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edit_dialog.o edit_dialog.cpp

form1.o: form1.cpp form1.h \
		qtlen.h \
		qtlencryptedsocket.h \
		defines.h \
		qtlen_parser.h \
		widgets/systrayicon.h \
		widgets/qtlenmainwindow.hpp \
		widgets/qtlenrosterbox.hpp \
		widgets/qtlenrosteritemdelegate.hpp \
		widgets/qtlenrosteritem.hpp \
		widgets/qtlenstatuslabel.hpp \
		widgets/qtlentextedit.hpp \
		widgets/qtlenavatarlabel.hpp \
		chat_manager.h \
		widgets/qtlenchatcontainer.hpp \
		widgets/qtlenchatwindow.hpp \
		roster_manager.h \
		avatarsmanager.hpp \
		historymanager.hpp \
		debug.h \
		ui_debug.h \
		edit_dialog.h \
		ui_user_edit.h \
		settings_dialog.h \
		info_edit.h \
		ui_info_edit.h \
		widgets/qtlensearchdialog.hpp \
		widgets/qtlensearchresultbox.hpp \
		widgets/qtlenpublicchatswindow.hpp \
		sha1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o form1.o form1.cpp

info_edit.o: info_edit.cpp info_edit.h \
		ui_info_edit.h \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o info_edit.o info_edit.cpp

main.o: main.cpp form1.h \
		qtlen.h \
		qtlencryptedsocket.h \
		defines.h \
		qtlen_parser.h \
		widgets/systrayicon.h \
		widgets/qtlenmainwindow.hpp \
		widgets/qtlenrosterbox.hpp \
		widgets/qtlenrosteritemdelegate.hpp \
		widgets/qtlenrosteritem.hpp \
		widgets/qtlenstatuslabel.hpp \
		widgets/qtlentextedit.hpp \
		widgets/qtlenavatarlabel.hpp \
		chat_manager.h \
		widgets/qtlenchatcontainer.hpp \
		widgets/qtlenchatwindow.hpp \
		roster_manager.h \
		avatarsmanager.hpp \
		historymanager.hpp \
		debug.h \
		ui_debug.h \
		edit_dialog.h \
		ui_user_edit.h \
		settings_dialog.h \
		info_edit.h \
		ui_info_edit.h \
		widgets/qtlensearchdialog.hpp \
		widgets/qtlensearchresultbox.hpp \
		widgets/qtlenpublicchatswindow.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qtlen.o: qtlen.cpp qtlen.h \
		qtlencryptedsocket.h \
		defines.h \
		qtlen_parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtlen.o qtlen.cpp

qtlen_parser.o: qtlen_parser.cpp qtlen_parser.h \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtlen_parser.o qtlen_parser.cpp

roster_manager.o: roster_manager.cpp roster_manager.h \
		defines.h \
		widgets/qtlenrosterbox.hpp \
		widgets/qtlenrosteritemdelegate.hpp \
		widgets/qtlenrosteritem.hpp \
		widgets/systrayicon.h \
		avatarsmanager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o roster_manager.o roster_manager.cpp

settings_dialog.o: settings_dialog.cpp settings_dialog.h \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings_dialog.o settings_dialog.cpp

sha1.o: sha1.cpp sha1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sha1.o sha1.cpp

qtlenchatwindow.o: widgets/qtlenchatwindow.cpp widgets/qtlenchatwindow.hpp \
		widgets/qtlentextedit.hpp \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtlenchatwindow.o widgets/qtlenchatwindow.cpp

qtlenmainwindow.o: widgets/qtlenmainwindow.cpp widgets/qtlenmainwindow.hpp \
		widgets/qtlenrosterbox.hpp \
		widgets/qtlenrosteritemdelegate.hpp \
		widgets/qtlenrosteritem.hpp \
		defines.h \
		widgets/qtlenstatuslabel.hpp \
		widgets/qtlentextedit.hpp \
		widgets/qtlenavatarlabel.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtlenmainwindow.o widgets/qtlenmainwindow.cpp

qtlenrosterbox.o: widgets/qtlenrosterbox.cpp widgets/qtlenrosterbox.hpp \
		widgets/qtlenrosteritemdelegate.hpp \
		widgets/qtlenrosteritem.hpp \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtlenrosterbox.o widgets/qtlenrosterbox.cpp

qtlentextedit.o: widgets/qtlentextedit.cpp widgets/qtlentextedit.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtlentextedit.o widgets/qtlentextedit.cpp

systrayicon.o: widgets/systrayicon.cpp widgets/systrayicon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o systrayicon.o widgets/systrayicon.cpp

qtlensearchresultbox.o: widgets/qtlensearchresultbox.cpp widgets/qtlensearchresultbox.hpp \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtlensearchresultbox.o widgets/qtlensearchresultbox.cpp

qtlensearchdialog.o: widgets/qtlensearchdialog.cpp widgets/qtlensearchdialog.hpp \
		defines.h \
		widgets/qtlensearchresultbox.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtlensearchdialog.o widgets/qtlensearchdialog.cpp

avatarsmanager.o: avatarsmanager.cpp avatarsmanager.hpp \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o avatarsmanager.o avatarsmanager.cpp

historymanager.o: historymanager.cpp historymanager.hpp \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o historymanager.o historymanager.cpp

qtlenstatuslabel.o: widgets/qtlenstatuslabel.cpp widgets/qtlenstatuslabel.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtlenstatuslabel.o widgets/qtlenstatuslabel.cpp

qtlenavatarlabel.o: widgets/qtlenavatarlabel.cpp widgets/qtlenavatarlabel.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtlenavatarlabel.o widgets/qtlenavatarlabel.cpp

qtlenpublicchatswindow.o: widgets/qtlenpublicchatswindow.cpp widgets/qtlenpublicchatswindow.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtlenpublicchatswindow.o widgets/qtlenpublicchatswindow.cpp

qtlenpublicchatsmanager.o: qtlenpublicchatsmanager.cpp qtlenpublicchatsmanager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtlenpublicchatsmanager.o qtlenpublicchatsmanager.cpp

qtlencryptedsocket.o: qtlencryptedsocket.cpp qtlencryptedsocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtlencryptedsocket.o qtlencryptedsocket.cpp

qtlenchatcontainer.o: widgets/qtlenchatcontainer.cpp widgets/qtlenchatcontainer.hpp \
		widgets/qtlenchatwindow.hpp \
		widgets/qtlentextedit.hpp \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtlenchatcontainer.o widgets/qtlenchatcontainer.cpp

qtlenrosteritem.o: widgets/qtlenrosteritem.cpp widgets/qtlenrosteritem.hpp \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtlenrosteritem.o widgets/qtlenrosteritem.cpp

qtlenrosteritemdelegate.o: widgets/qtlenrosteritemdelegate.cpp widgets/qtlenrosteritemdelegate.hpp \
		widgets/qtlenrosteritem.hpp \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtlenrosteritemdelegate.o widgets/qtlenrosteritemdelegate.cpp

moc_chat_manager.o: moc_chat_manager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chat_manager.o moc_chat_manager.cpp

moc_debug.o: moc_debug.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_debug.o moc_debug.cpp

moc_edit_dialog.o: moc_edit_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_edit_dialog.o moc_edit_dialog.cpp

moc_form1.o: moc_form1.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_form1.o moc_form1.cpp

moc_info_edit.o: moc_info_edit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_info_edit.o moc_info_edit.cpp

moc_qtlen.o: moc_qtlen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtlen.o moc_qtlen.cpp

moc_roster_manager.o: moc_roster_manager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_roster_manager.o moc_roster_manager.cpp

moc_settings_dialog.o: moc_settings_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settings_dialog.o moc_settings_dialog.cpp

moc_qtlenchatwindow.o: moc_qtlenchatwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtlenchatwindow.o moc_qtlenchatwindow.cpp

moc_qtlenmainwindow.o: moc_qtlenmainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtlenmainwindow.o moc_qtlenmainwindow.cpp

moc_qtlenrosterbox.o: moc_qtlenrosterbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtlenrosterbox.o moc_qtlenrosterbox.cpp

moc_qtlentextedit.o: moc_qtlentextedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtlentextedit.o moc_qtlentextedit.cpp

moc_systrayicon.o: moc_systrayicon.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_systrayicon.o moc_systrayicon.cpp

moc_qtlensearchresultbox.o: moc_qtlensearchresultbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtlensearchresultbox.o moc_qtlensearchresultbox.cpp

moc_qtlensearchdialog.o: moc_qtlensearchdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtlensearchdialog.o moc_qtlensearchdialog.cpp

moc_avatarsmanager.o: moc_avatarsmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_avatarsmanager.o moc_avatarsmanager.cpp

moc_historymanager.o: moc_historymanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_historymanager.o moc_historymanager.cpp

moc_qtlenstatuslabel.o: moc_qtlenstatuslabel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtlenstatuslabel.o moc_qtlenstatuslabel.cpp

moc_qtlenavatarlabel.o: moc_qtlenavatarlabel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtlenavatarlabel.o moc_qtlenavatarlabel.cpp

moc_qtlencryptedsocket.o: moc_qtlencryptedsocket.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtlencryptedsocket.o moc_qtlencryptedsocket.cpp

moc_qtlenchatcontainer.o: moc_qtlenchatcontainer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtlenchatcontainer.o moc_qtlenchatcontainer.cpp

moc_qtlenrosteritemdelegate.o: moc_qtlenrosteritemdelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtlenrosteritemdelegate.o moc_qtlenrosteritemdelegate.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

