# #####################################################################
# Automatically generated by qmake (2.01a) niedz. lut 15 06:38:42 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += . \
    widgets
INCLUDEPATH += . \
    widgets
QT += xml \
    network \
    sql

# Input
HEADERS += chat_manager.h \
    debug.h \
    defines.h \
    edit_dialog.h \
    form1.h \
    info_edit.h \
    qtlen.h \
    qtlen_parser.h \
    roster_manager.h \
    settings_dialog.h \
    sha1.h \
    widgets/qtlenchatwindow.hpp \
    widgets/qtlenmainwindow.hpp \
    widgets/qtlenrosterbox.hpp \
    widgets/qtlentextedit.hpp \
    widgets/systrayicon.h \
    widgets/qtlensearchresultbox.hpp \
    widgets/qtlensearchdialog.hpp \
    avatarsmanager.hpp \
    historymanager.hpp \
    widgets/qtlenstatuslabel.hpp \
    widgets/qtlenavatarlabel.hpp \
    widgets/qtlenpublicchatswindow.hpp \
    qtlenpublicchatsmanager.hpp
FORMS += config.ui \
    debug.ui \
    info_edit.ui \
    user_edit.ui
SOURCES += chat_manager.cpp \
    debug.cpp \
    edit_dialog.cpp \
    form1.cpp \
    info_edit.cpp \
    main.cpp \
    qtlen.cpp \
    qtlen_parser.cpp \
    roster_manager.cpp \
    settings_dialog.cpp \
    sha1.cpp \
    widgets/qtlenchatwindow.cpp \
    widgets/qtlenmainwindow.cpp \
    widgets/qtlenrosterbox.cpp \
    widgets/qtlentextedit.cpp \
    widgets/systrayicon.cpp \
    widgets/qtlensearchresultbox.cpp \
    widgets/qtlensearchdialog.cpp \
    avatarsmanager.cpp \
    historymanager.cpp \
    widgets/qtlenstatuslabel.cpp \
    widgets/qtlenavatarlabel.cpp \
    widgets/qtlenpublicchatswindow.cpp \
    qtlenpublicchatsmanager.cpp
RESOURCES += icons.qrc
TRANSLATIONS = qtlen4_pl.ts
